name       : iortcw
version    : 1.51c
release    : 7
source     :
    - https://github.com/iortcw/iortcw/archive/1.51c.tar.gz : 0f6c136db1e5c6115e044190655163b9784bbef9b0667ec2a8900abd79565e83
license    : GPL-3.0-or-later
component  : games.action
summary    : Return To Castle Wolfenstein source port
description: |
    The intent of this project is to provide a baseline RTCW which may be used for further development and fun.
    Game data must be placed in ~/.wolf/main/.
builddeps  :
    - pkgconfig(freetype2)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(openal)
    - pkgconfig(opusfile)
    - pkgconfig(sdl2)
environment: |
    export \
        COPYDIR=$installdir/usr/share/iortcw \
        USE_CURL_DLOPEN=0 \
        USE_OPENAL_DLOPEN=0 \
        USE_INTERNAL_LIBS=0
build      : |
    %make -C SP
    %make -C MP
install    : |
    %make -C SP copyfiles
    %make -C MP copyfiles

    install -Dm00644 SP/misc/iortcw.svg $installdir/usr/share/icons/hicolor/scalable/apps/iortcw.svg

    install -Dm00644 $pkgfiles/iowolfsp.desktop $installdir/usr/share/applications/iowolfsp.desktop
    install -Dm00644 $pkgfiles/iowolfmp.desktop $installdir/usr/share/applications/iowolfmp.desktop
